### ISSUE TITLE
Not able to log to console after calling sitemap-static

### ISSUE THREAD

**Issue by danhalliday** [tmcw/sitemap-static#13]
Thank you for this useful tool. I'm finding after I call sitemap-static, `console.log` does not print to the terminal. Any ideas?

**Comment by tmcw** [comment]
I'd need more detail to debug this issue. Can you provide a code example?

**Comment by danhalliday** [comment]
Sure, I’ll get a simplified example done.

**Comment by tmcw** [comment]
Closing, feel free to reopen if there's a minimal example.
